local set = vim.opt_local
set.colorcolumn = "108"
vim.o.textwidth = 108
vim.o.wrapmargin = 108
set.formatoptions = set.formatoptions + "t"
set.shiftwidth = 2
set.tabstop = 2
vim.o.linebreak = false
set.number = false
set.relativenumber = false
